-- Reconciles the remaining differences between what `prisma migrate deploy`
-- produces and what schema.prisma declares. These objects reached deployed
-- databases through `prisma db push`, so every statement is guarded and this is
-- a no-op where they already exist.
--
-- Deliberately NOT included: dropping the legacy `accounts`/`sessions` tables,
-- the pre-Clerk `users` auth columns, or the raw-SQL `search_vector` columns and
-- their GIN indexes. `migrate diff` reports all of those as drift — the search
-- vectors because Prisma cannot model them, the legacy columns because they are
-- unused leftovers. Dropping them is a data-destroying change that belongs in a
-- deliberate cleanup, not a reconciliation.

-- 20260313180000_add_character_roleplay_fields created "example_dialogues", but
-- the schema field `exampleDialogues` has no @map, so Prisma looks for
-- "exampleDialogues". Any migrate-deployed database would fail at runtime on
-- every character read. Add the correct column, carry over any data written
-- under the wrong name, then drop the stray.
ALTER TABLE "characters" ADD COLUMN IF NOT EXISTS "exampleDialogues" TEXT;

DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'characters' AND column_name = 'example_dialogues'
  ) THEN
    UPDATE "characters"
      SET "exampleDialogues" = "example_dialogues"
      WHERE "exampleDialogues" IS NULL AND "example_dialogues" IS NOT NULL;
    ALTER TABLE "characters" DROP COLUMN "example_dialogues";
  END IF;
END $$;

-- Creator monetization Stripe linkage
ALTER TABLE "creator_subscriptions" ADD COLUMN IF NOT EXISTS "stripe_checkout_session_id" TEXT;
ALTER TABLE "creator_subscriptions" ADD COLUMN IF NOT EXISTS "stripe_current_period_end" TIMESTAMP(3);
ALTER TABLE "creator_subscriptions" ADD COLUMN IF NOT EXISTS "stripe_customer_id" TEXT;
ALTER TABLE "creator_subscriptions" ADD COLUMN IF NOT EXISTS "stripe_subscription_id" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "creator_subscriptions_stripe_subscription_id_key"
  ON "creator_subscriptions"("stripe_subscription_id");
CREATE UNIQUE INDEX IF NOT EXISTS "creator_subscriptions_stripe_checkout_session_id_key"
  ON "creator_subscriptions"("stripe_checkout_session_id");

ALTER TABLE "creator_tips" ADD COLUMN IF NOT EXISTS "stripe_checkout_session_id" TEXT;
ALTER TABLE "creator_tips" ADD COLUMN IF NOT EXISTS "stripe_payment_intent_id" TEXT;
ALTER TABLE "creator_tips" ALTER COLUMN "status" SET DEFAULT 'PENDING';

CREATE UNIQUE INDEX IF NOT EXISTS "creator_tips_stripe_checkout_session_id_key"
  ON "creator_tips"("stripe_checkout_session_id");
CREATE UNIQUE INDEX IF NOT EXISTS "creator_tips_stripe_payment_intent_id_key"
  ON "creator_tips"("stripe_payment_intent_id");
CREATE INDEX IF NOT EXISTS "creator_tips_creatorId_status_idx"
  ON "creator_tips"("creatorId", "status");

-- Message read-path indexes declared in the schema but never migrated
CREATE INDEX IF NOT EXISTS "messages_senderId_createdAt_idx"
  ON "messages"("senderId", "createdAt");
CREATE INDEX IF NOT EXISTS "messages_conversationId_isDeleted_createdAt_idx"
  ON "messages"("conversationId", "isDeleted", "createdAt");

-- The schema has no @default on UserPersona.id; ids are generated by the client.
ALTER TABLE "user_personas" ALTER COLUMN "id" DROP DEFAULT;

-- Scan index for the GDPR deletion cron, which sweeps users by deletion state.
CREATE INDEX IF NOT EXISTS "users_deletionRequested_deletionScheduledFor_idx"
  ON "users"("deletionRequested", "deletionScheduledFor");
